# -*- mode: python ; coding: utf-8 -*-

import sys
import os

block_cipher = None

# Lista de todos os módulos e pacotes de domínio do GeoAlvo
hidden_imports = [
    'ativo_imobilizado',
    'ativo_imobilizado.models',
    'ativo_imobilizado.repository',
    'ativo_imobilizado.service',
    'ativo_imobilizado.view',
    'ativo_imobilizado.categoria_bens_view',
    'ativo_imobilizado.localizacao_fisica_view',
    'ativo_imobilizado.classificacao_bens_view',
    'autenticacao',
    'categorias',
    'categorias.cadcategoria_view',
    'cargos',
    'cargos.models',
    'cargos.repository',
    'cargos.service',
    'cargos.cadcargo_view',
    'centro_controle',
    'centro_controle.models',
    'centro_controle.repository',
    'centro_controle.service',
    'centro_controle.view',
    'configcod',
    'configuracoes',
    'configuracoes.alvo_api_config',
    'configuracoes.alvo_api_view',
    'consultas',
    'consultas.imediatas_view',
    'consultas.models',
    'consultas.repository',
    'consultas.service',
    'consultas.view',
    'openpyxl',
    'contabilidade',
    'contabilidade.view_debxcred',
    'contabilidade.view_exclusao',
    'core',
    'core.validators',
    'core.viacep',
    'core.email_service',
    'core.recursos',
    'core.criptografia',
    'core.error_logger',
    'core.date_utils',
    'core.permission_manager',
    'core.schema_checker',
    'core.sessao',
    'cores',
    'crm',
    'dashboard',
    'dashboard.gauge',
    'dashboard.models',
    'dashboard.repository',
    'dashboard.service',
    'dashboard.view',
    'departamentos',
    'dioceses',
    'empresas',
    'entidades',
    'entidades.api_client',
    'entidades.cadentidade_view',
    'entidades.database',
    'entidades.documentos_teste',
    'entidades.models',
    'entidades.repository',
    'entidades.service',
    'entidades.view',
    'estacoes',
    'estoque',
    'estoque.models',
    'estoque.repository',
    'estoque.service',
    'estoque.requisicoes_view',
    'estoque.movimentacao_view',
    'estoque.consultas_view',
    'estoque.nova_requisicao_view',
    'estoque.almoxarifados_repository',
    'estoque.almoxarifados_view',
    'estoque.relatorios_almoxarifado_view',
    'eventos',
    'eventos.importer',
    'fiscal',
    'licenciamento',
    'licenciamento.models',
    'licenciamento.repository',
    'licenciamento.service',
    'licenciamento.view',
    'localidades',
    'lotes',
    'lotes.models',
    'lotes.repository',
    'lotes.service',
    'lotes.view',
    'lotes.alerta_vencimento_view',
    'marcas',
    'marcas.models',
    'marcas.repository',
    'marcas.service',
    'marcas.view',
    'matchcode',
    'nomesamigaveis',
    'permissoes',
    'permissoes.view',
    'permissoes.contas_fin_view',
    'permissoes.desligamento_view',
    'produtos',
    'produtos.grupos_view',
    'produtos.models',
    'produtos.repository',
    'produtos.service',
    'produtos.view',
    'relatorios',
    'relatorios.generator',
    'contas_a_pagar',
    'contas_a_pagar.models',
    'contas_a_pagar.repository',
    'contas_a_pagar.service',
    'contas_a_pagar.view',
    'usuarios',
    'vindi',
    'vindi.dashboard_view',
    'savic',
    'savic.models',
    'savic.repository',
    'savic.service',
    'savic.view',
    'savic.moderacao_models',
    'savic.moderacao_repository',
    'savic.moderacao_service',
    'savic.moderacao_view',
    'pymysql',
    'pymysql.cursors',
    'config_banco',
    'toolbar_geoalvo',
    'logon',
    'seleciona_empresa',
    'splash',
    'geoalvo',
    'keyring',
    'keyring.backends',
    'keyring.backends.Windows',
    'PIL',
    'PIL.Image',
    'PIL.ImageTk',
    'pyodbc',
    'requests',
    'sqlite3',
    'tkinter',
    'tkinter.ttk',
    'tkinter.messagebox',
    'tkinter.filedialog',
    'tkinter.scrolledtext',
    'fpdf',
]

# Dados e ativos adicionais (imagens, logos, fundos)
datas = [
    ('Imagens', 'Imagens'),
    ('GeoApolo_Icon.ico', '.'),
    ('faviconrcc.ico', '.'),
]

a = Analysis(
    ['splash.py'],
    pathex=['.'],
    binaries=[],
    datas=datas,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['test', 'tests', 'PyQt6', 'PySide6', 'selenium', 'pdfminer', 'pdfplumber', 'pypdfium2'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
    optimize=1,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='GeoAlvo',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='faviconrcc.ico',
)
