# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['logon.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('Imagens', 'Imagens'),
        ('GeoApolo_Icon.ico', '.'),
        ('faviconrcc.ico', '.'),
    ],
    hiddenimports=[
        'seleciona_empresa',
        'geoalvo',
        'config_banco',
        'toolbar_geoalvo',
        'savic',
        'savic.models',
        'savic.repository',
        'savic.service',
        'savic.view',
        'pymysql',
        'pymysql.cursors',
        'entidades',
        'entidades.database',
        'empresas',
        'usuarios',
        'keyring',
        'keyring.backends',
        'keyring.backends.Windows',
        'pyodbc',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='logon',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='faviconrcc.ico',
)
